# Generated by Django 4.1.4 on 2023-03-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
