# Generated by Django 4.1.4 on 2023-03-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_skill_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
