# Generated by Django 4.1.4 on 2023-03-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_goal_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
