# Generated by Django 4.1.4 on 2023-03-11 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0007_skill_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='progress',
        ),
    ]
